name: Prepare dependencies
description: 'composite run action'
inputs:
    env-vars:
      description: 'Env vars to set'
      required: true
    cache-name:
      description: Cache name to get/set
      required: true
outputs:
  cache-name:
    description: "Warmup cache result name"
    value: ${{ steps.setvars.outputs.cache-name }}

runs:
  using: 'composite'
  steps:
    - name: Set cache name
      shell: bash
      id: setvars
      run: echo "::set-output name=cache-name::${{ inputs.cache-name }}"
    
    - name: Test env var setter
      shell: bash
      run: |
        echo "<<EOL
        ${{ inputs.env-vars }}
        EOL" >> $GITHUB_ENV

    - name: print env
      shell: bash
      run: echo "$SOMEVALUE"

    - name: print env2
      shell: bash
      run: echo "$SOMEVALUE2"