name: Prepare dependencies
description: 'composite run action'
inputs:
    env-vars:
      description: 'Env vars to set'
      required: true
    cache-name:
      description: Cache name to get/set
      required: true
outputs:
  cache-name:
    description: "Warmup cache result name"
    value: ${{ steps.setvars.outputs.cache-name }}

runs:
  using: 'composite'
  steps:
    - name: Set cache name
      shell: bash
      id: setvars
      run: echo "::set-output name=cache-name::${{ inputs.cache-name }}"
    
    - name: Test env var setter
      shell: bash
      run: |
        cat >> $GITHUB_ENV << \EOL
        ${{ inputs.env-vars }}
        EOL

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: 16
          cache: yarn

    - name: Restore node modules cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
          path: node_modules
          key: ${{ inputs.cache-name }}

    - if: steps.yarn-cache.outputs.cache-hit != 'true'
      name: Install dependencies
      shell: bash
      run: yarn install --prefer-offline --frozen-lockfile

    - name: print env
      shell: bash
      run: echo "${{ env.SOMEVALUE }}"

    - name: print env2
      shell: bash
      run: echo "${{ env.SOMEVALUE2 }}"

    - name: print npm_token
      shell: bash
      run: echo "${{ env.NPM_TOKEN }}"