name: CI+CD (push)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'Dockerfile.develop'
      - 'compose-develop.yml'
  workflow_dispatch:

jobs:
  warmup:
    name: Prepare dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node_modules
        id: warmup
        uses: ./.github/workflows/ci/warmup
        with:
          env-vars: |
            FOO=BAR
            BAZ=QUX
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          cache-name: ${{ runner.os }}-warmup-${{ hashFiles('**/yarn.lock') }}
      
      - name: Print step result
        run: echo "${{ steps.warmup.outputs.cache-name }}"


         foo if only one placeholder name is needed. Then they will use bar, and finally baz. If more are needed, there is qux, quux, quuz, corge, grault, garply, waldo, fred, plugh, xyzzy, and thud.